name: flutter_fundamental
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  flutter_secure_storage: ^3.3.1+1
  cupertino_icons: ^0.1.3
  bip39: ^1.0.3
  toast: ^0.1.5
  encrypt: ^4.0.0
  jaguar_jwt: ^2.1.6
  multi_currency:
    path: ../../multi_currency
  font_awesome_flutter: ^8.7.0
  http: ^0.12.0+4
  webview_flutter: ^0.3.19+8
  qr_flutter: ^3.2.0
  barcode_scan: ^2.0.1
  uni_links: ^0.2.0
  bip21: ^1.0.0
  screen_state: ^0.1.1
  url_launcher: ^5.4.2
  sqflite: ^1.2.1
  path: ^1.6.4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
